### ISSUE TITLE
Cannot package using cx_Freeze

### ISSUE THREAD

**Issue by ibell** [Julian/jsonschema#214]
I'll post a message on cx_Freeze lists too, but cx_Freeze cannot package jsonschema, and I was wondering whether you had any experience with this.

A simple minimal working example:
```
import sys
from cx_Freeze import setup, Executable

build_exe_options = {"packages": ["os"], "excludes": ["tkinter"]}

setup(  name = "test",
        version = "0.0",
        description = "My GUI application!",
        options = {"build_exe": build_exe_options},
        executables = [Executable("test.py")])
```
where the contents of ``test.py`` are simply
```
import jsonschema
```
I get the traceback:
```
running build
running build_exe
copying C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\bases\Console.exe -> build\exe.win-amd64-2.7\webfile_builder.exe
copying C:\Users\ihb\AppData\Local\Continuum\Miniconda\python27.dll -> build\exe.win-amd64-2.7\python27.dll
Stamped: build\exe.win-amd64-2.7\webfile_builder.exe
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    executables = [Executable("webfile_builder.py")])
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\dist.py", line 232, in run
    freezer.Freeze()
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 626, in Freeze
    self.compress, self.copyDependentFiles)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 526, in _WriteModules
    module.Create(finder)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\cx_Freeze\freezer.py", line 762, in Create
    module.file, module.name)
cx_Freeze.freezer.ConfigError: no file named sys (for module collections.sys)
```

**Comment by Julian** [comment]
Hey! Sorry you're having trouble.

Way way back in the day, someone submitted a ticket, which I think was about cx_Freeze -- I don't use it, but I'd have no problem supporting it if someone cares to submit a test case that actually ensures it stays working.

I don't know what your error means (well, I can guess, cx_Freeze isn't going to like sys because it isn't a module backed by a file, but I can't imagine that it doesn't have a way to cope with that) -- lemme know what they say on the mailing list and I'd love to help.

**Comment by ibell** [comment]
Seems there is a bug in cx_Freeze, I was able to work around it, but
hopefully they can fix it on their side

**Comment by Julian** [comment]
Ah, cool. Feel free to follow up if you need anything else.
