### ISSUE TITLE
Installation from pip fails under python 3.2.3

### ISSUE THREAD

**Issue by lepinkainen** [Julian/jsonschema#222]
```
Downloading/unpacking jsonschema
  Running setup.py egg_info for package jsonschema
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/users/shrike/projects/pyfibot3/build/jsonschema/setup.py", line 3, in <module>
        from jsonschema import __version__
      File "jsonschema/__init__.py", line 18, in <module>
        from jsonschema.validators import (
      File "jsonschema/validators.py", line 41
        if u"id" in cls.META_SCHEMA:
               ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/users/shrike/projects/pyfibot3/build/jsonschema/setup.py", line 3, in <module>

    from jsonschema import __version__

  File "jsonschema/__init__.py", line 18, in <module>

    from jsonschema.validators import (

  File "jsonschema/validators.py", line 41

    if u"id" in cls.META_SCHEMA:

           ^

SyntaxError: invalid syntax
```

Shouldn't jsonschema support python 3 or am I missing something?

**Comment by Julian** [comment]
Hi!

Support for 3.2 was dropped in 2.4.0 -- jsonschema supports 3.3+.

I'd suggest upgrading (or downgrading :) your python, or otherwise 2.3.0
should work.

**Comment by lepinkainen** [comment]
Damn Debian Stable, perpetually out of date. =)

I can work with that, thank you.
