### ISSUE TITLE
Unable to install jsonschema because of vcversioner dependency

### ISSUE THREAD

**Issue by gomezgoiri** [Julian/jsonschema#257]
I'm having problems installing jsonschema (versions 2.5.0 and 2.5.1). It seems that it cannot find _vcversioner_.

However, when I install _vnversioner_ before (``pip install vcversioner``) the problem disappears.

```
$ pip install jsonschema==2.5.0
Downloading/unpacking jsonschema==2.5.0
  Downloading jsonschema-2.5.0.tar.gz (50kB): 50kB downloaded
  Running setup.py egg_info for package jsonschema
    Download error on https://pypi.python.org/simple/vcversioner/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!
    Couldn't find index page for 'vcversioner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!
    No local packages or download links found for vcversioner
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/data/user-data/agg96/ptapi/build/jsonschema/setup.py", line 49, in <module>
        vcversioner={"version_module_paths" : ["jsonschema/_version.py"]},
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('vcversioner')
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/vcversioner/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!

Couldn't find index page for 'vcversioner' (maybe misspelled?)

Download error on https://pypi.python.org/simple/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!

No local packages or download links found for vcversioner

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/data/user-data/agg96/ptapi/build/jsonschema/setup.py", line 49, in <module>

    vcversioner={"version_module_paths" : ["jsonschema/_version.py"]},

  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve

    dist = best[req.key] = env.best_match(req, self, installer)

  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain

    return installer(requirement)

  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg

    return cmd.easy_install(req)

  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install

    raise DistutilsError(msg)

distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('vcversioner')
```

**Comment by Julian** [comment]
I see some SSL errors in there:

>    Download error on https://pypi.python.org/simple/vcversioner/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!

What version of openssl is your Python compiled against (and more broadly where's your Python from)? Seems likely that this isn't unique to vcversioner, you'll probably have issues more generally connecting to PyPI

**Comment by gomezgoiri** [comment]
The OpenSSL version is the 1.0.1e and the Python one 2.7.5 (the default package which comes with RHEL7).

It might be an HTTP proxy configuration issue (it is the cause of our problems 95% of the times), but if this would be the case I don't understand why the following works:
 * First installing _vcversioner_ (independently) and then installing _jsonschema_.
 * (the installation of _jsonschema_ version 2.4.0 and lower also works, but back then _vcversioner_ wasn't required by the _setup.py_, right?)

**Comment by Julian** [comment]
I'm not 100% sure either, I'll think about it a bit, but possibly it has to do with the fact that for the former case (installing it "independently"), pip handles the install, whereas for `install_requires`, setuptools does.

**Comment by Julian** [comment]
I don't think I have enough info to reproduce this :/ -- if you happen to be able to boil this down, please let me know.

**Comment by mkloveyy** [comment]
You need to run this first:
`pip install vcversioner `

then you can succeed by:
`pip install jsonschema`
