### ISSUE TITLE
UnicodeDecodeError: 'uf8' codec doesn't seem to be enough, option to pass in then default it?

### ISSUE THREAD

**Issue by dandeezy** [Julian/jsonschema#290]
EDIT: Created this issue on the wrong repo. It's csvdiffer.py which uses jsondumps that doesn't have this UTF flag. Please ignore below but point me to the def dump() method so I can see how I can pass in the UTF-16 parameter. Sorry! 

-------------------------------------

jsonschema.dump() on line 196 of patch.py doesn't take a Unicode parameter. I think I need UTF-16 on my data and there's no option to pass this in. When I get a chance this weekend I'll do a PR to pass this option via command line and default to utf-8 

Comically it fails on the an episode of the Kardashians 

Full Stack Trace: 
```
        "description": {
          "from": "Khloe struggles with moving out of her house; Bruce attempts to bond with Brody; Kourtney, Kim, and Khloe head to NY to chec
k on DASH.",
          "to": Traceback (most recent call last):
  File "C:\Python\2.7.9\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python\2.7.9\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python\2.7.9\Scripts\csvdiff.exe\__main__.py", line 9, in <module>
  File "C:\Python\2.7.9\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python\2.7.9\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "C:\Python\2.7.9\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python\2.7.9\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "C:\Python\2.7.9\lib\site-packages\csvdiff\__init__.py", line 140, in csvdiff_cmd
    compact=compact)
  File "C:\Python\2.7.9\lib\site-packages\csvdiff\__init__.py", line 152, in _diff_files_to_stream
    patch.save(diff, ostream, compact=compact)
  File "C:\Python\2.7.9\lib\site-packages\csvdiff\patch.py", line 196, in save
    json.dump(diff, stream, **flags)
  File "C:\Python\2.7.9\lib\json\__init__.py", line 189, in dump
    for chunk in iterable:
  File "C:\Python\2.7.9\lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\Python\2.7.9\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Python\2.7.9\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Python\2.7.9\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Python\2.7.9\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Python\2.7.9\lib\json\encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 4: invalid continuation byte
```

**Comment by Julian** [comment]
I can't tell from your EDIT. Are you saying this is a mistake or not?

**Comment by dandeezy** [comment]
There's no mistake. I think csvdiffer failed to pass the escape_ascii flag when output stream is STDOUT. Please close this.

**Comment by dandeezy** [comment]
Actually it's called ensure_ascii=False to json.dump(). (For anybody else running into this issue)
