### ISSUE TITLE
AttributeError: '_io.TextIOWrapper' object has no attribute 'get'

### ISSUE THREAD

**Issue by Gujjar95** [Julian/jsonschema#384]
json schema error AttributeError: '_io.TextIOWrapper' object has no attribute 'get'
My files 
```{ 
{
	"sender" : 6
	"receiver" : 4,
	"transaction_type" : "same",
	"transaction_amount" : "10",
	"transaction_status" : "pending",
	"transaction_receiver_address":"",
	"transaction_sender_address" : "",
	"transaction_currency_involved" : "Usd"
} ```
Below is my json schema.

``` {
 "definitions": {},
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "sender": {
      "id": "/properties/sender",
      "type": "integer",
      "title": "The Sender Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0
    },
    "receiver": {
      "id": "/properties/receiver",
      "type": "integer",
      "title": "The Receiver Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0
    },
    "transaction_type": {
      "id": "/properties/transaction_type",
      "type": "string",
      "title": "The Transaction_type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "transaction_amount": {
      "id": "/properties/transaction_amount",
      "type": "string",
      "title": "The Transaction_amount Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "transaction_status": {
      "id": "/properties/transaction_status",
      "type": "string",
      "title": "The Transaction_status Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "transaction_receiver_address": {
      "id": "/properties/transaction_receiver_address",
      "type": "string",
      "title": "The Transaction_receiver_address Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "transaction_sender_address": {
      "id": "/properties/transaction_sender_address",
      "type": "string",
      "title": "The Transaction_sender_address Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "transaction_currency_involved": {
      "id": "/properties/transaction_currency_involved",
      "type": "string",
      "title": "The Transaction_currency_involved Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    }
  }
} ```

**Comment by Julian** [comment]
Hi. Please include full reproducible code + traceback.

**Comment by Gujjar95** [comment]
Below is my Code, Traceback and schema and instances i have posted above
```
def post(self, request, id):
    	received_json_data = json.loads(request.body.decode("utf-8"))
    	validate(instance = received_json_data, schema = schema)
    	sender = User.objects.filter(pk=int(received_json_data['sender'])).first()
    	receiver = User.objects.filter(pk=int(received_json_data['receiver'])).first()
    	transaction_type = received_json_data['transaction_type']
    	transaction_status = received_json_data['transaction_status']
    	transaction_amount = int(received_json_data['transaction_amount'])
    	transaction_receiver_address = received_json_data['transaction_receiver_address']
    	transaction_sender_address = received_json_data['transaction_sender_address']
    	transaction_currency_involved = received_json_data['transaction_currency_involved']
    	if sender is not None:
    		temp_sender = WalletBalance.objects.get(wallet=Wallet.objects.filter(user=sender),wallet_currency=transaction_currency_involved)
    		if temp_sender.currency_address != transaction_sender_address:
    			return HttpResponse("Sender address does not matches")
    		if transaction_amount > temp_sender.balance:
    			return HttpResponse("Insufficient balance")
    	if receiver is not None:
    		temp_receiver = WalletBalance.objects.get(wallet=Wallet.objects.filter(user=receiver),wallet_currency=transaction_currency_involved).currency_address
    		if temp_receiver != transaction_receiver_address:
    			return HttpResponse("Receiver address does not matches")
    	transaction_new = Transaction(sender=sender, receiver=receiver, transaction_type=transaction_type,transaction_status=transaction_status, transaction_amount=transaction_amount,transaction_sender_address=transaction_sender_address,transaction_receiver_address=transaction_receiver_address,transaction_currency_involved=transaction_currency_involved)
    	transaction_new.save()
    	return HttpResponse("OK")
```
Trace back
```
Traceback (most recent call last):
  File "/home/gujjar/start1/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/gujjar/start1/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/gujjar/start1/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gujjar/start1/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gujjar/start1/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gujjar/tempry/check/apis/views.py", line 166, in post
    validate(instance = received_json_data, schema = schema)
  File "/home/gujjar/start1/venv/lib/python3.5/site-packages/jsonschema/validators.py", line 539, in validate
    cls = validator_for(schema)
  File "/home/gujjar/start1/venv/lib/python3.5/site-packages/jsonschema/validators.py", line 484, in validator_for
    return meta_schemas.get(schema.get(u"$schema", u""), default)
AttributeError: '_io.TextIOWrapper' object has no attribute 'get'
```

**Comment by Julian** [comment]
@Gujjar95 thanks, but I can't reproduce with that.

By reproducible -- I need code I can run that is [self contained](http://sscce.org/).

Your issue is going to be somewhere you passing in a TextWrapper, but in order to see where, I need the above.

**Comment by Gujjar95** [comment]
@Julian 
Sorry for the above, I am new to the community and learning all terminology.
Above method is an API call for post.Without validating function everything is working fine.So pb is arising after adding the validate.in the validate I am calling instance and schema which I posted in the first comment.
If you need full code then it is too many files to post here.

**Comment by Julian** [comment]
No worries, but without a fully reproducible set of code I can't really help -- you need to work on stripping away all the parts of your code that are unrelated and provide a minimal, self contained example.

I can tell from your traceback that you must be doing something like passing in `open(someschemafile)` rather than the actual contents of the file, but when filing issues you need to do a bit of work upfront to reduce down to something that you can share here if you can't find your issue yourself.

Hopefully the above is enough to point you in the right direction.

**Comment by Gujjar95** [comment]
yup you are right got it now ,
```
__location__ = os.path.realpath(
    os.path.join(os.getcwd(), os.path.dirname('views.py')))
schema = open(os.path.join(__location__,'apis/json_schema.json'))
```

**Comment by catb0t** [comment]
https://stackoverflow.com/help/mcve
