### ISSUE TITLE
Arrays cannot be validated in some cases

### ISSUE THREAD

**Issue by KOLANICH** [Julian/jsonschema#390]
```python
{
				"formats":{
					"test.py": {"path":"test.ksy"},
					"postprocess":["permissiveDecoding"], #here
					"flags": ["--ksc-json-output"] #here
				},
				"formatsRepo": {
					"git" : str(kscDirs.formats),
					"localPath" : testsDir / "formats",
					"update": True
				},
				"outputDir": testsDir / "output",
				"inputDir": testsDir / "ksys",
				"search": True
			}
}
```

fails validation against the schema https://github.com/KOLANICH/kaitaiStructCompile.py/blob/master/kaitaiStructCompile/config.schema.json

**Comment by Julian** [comment]
Hi. Please include your full code + traceback.

Thanks.

**Comment by KOLANICH** [comment]
The arrays failed validation are marked by comments. The rest of code is irrelevant.

**Comment by Julian** [comment]
That doesn't change my comment :), please include a [minimal example of code and traceback](http://sscce.org/), that I can just paste and run. Your original comment doesn't have enough information.

**Comment by lambdalisue** [comment]
I had the similar issue with the following code

```python
import jsonschema

SCHEMA = {
    'type': 'object',
    'properties': {
        'word': {
            'type': 'string',
            'pattern': '^HELLO$',
        },
        'items': {
            'type': 'array',
            'item': {
                'type': 'string',
                'pattern': '^HELLO$',
            }
        }
    }
}

data = {
    'items': [
        'HELLO',
        'HELLO',
        'HELLO',
    ],
}
print('Should be OK')
jsonschema.validate(data, SCHEMA)
print('Success')

data = {
    'items': [
        'HELLO',
        'world',
        'HELLO',
    ],
}
print('Should raise ValidationError (1)')
jsonschema.validate(data, SCHEMA)
print('Success')

data = {
    'word': 'world',
}
print('Should raise ValidationError (2)')
jsonschema.validate(data, SCHEMA)
print('Success')
```

The code above does not raise exception on (1) but (2)

```
Should be OK
Success
Should raise ValidationError (1)
Success
Should raise ValidationError (2)
Traceback (most recent call last):
  File "/Users/alisue/wk/test.py", line 46, in <module>
    jsonschema.validate(data, SCHEMA)
  File "/Users/alisue/wk/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/Users/alisue/wk/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'world' does not match '^HELLO$'

Failed validating 'pattern' in schema['properties']['word']:
    {'pattern': '^HELLO$', 'type': 'string'}

On instance['word']:
    'world'
```

**Comment by Julian** [comment]
Your schema typos "items" as "item".

**Comment by lambdalisue** [comment]
Oops sorry. I thought the schema is validated automatically in validate function. Is there any way to validate the scheme itself from "$sheme" attribute?

**Comment by Julian** [comment]
Your schema is valid, it just doesn't invalidate those instances -- additional properties are allowed in JSON schemas

**Comment by lambdalisue** [comment]
ic. thanks!

**Comment by Julian** [comment]
Going to close this because I'd presume even the original is some sort of user error when reduced to a small example, but @KOLANICH feel free to follow up if you think there's an actual issue.
