### ISSUE TITLE
jsonschema validator issue -- validate a wrong schema

### ISSUE THREAD

**Issue by fantamiracle** [Julian/jsonschema#512]
```
>>> import jsonschema
>>> jsonschema.__version__
'2.6.0'
>>> event = {
   "event": "entry.u",
   "timestamp": 1546467787.4796588,
   "data": {
     "orgId": 316,
     "requestId": 1128121473,
     "entryIds": [
       98
     ]
   }
 }
>>> t = {
   "properties": {
     "event": {
       "enum": [
         "un",
         "entry.u"
       ]
     },
     "data": {
       "required": ["entryIds"],
       "properties": {
         "entryIds": {
           "contains": {
             "enum": [
               980
             ]
           }
         }
       }
     }
   },
   "required": [
     "event"
   ]
 }
>>> jsonschema.validate(event, t)
>>>
```

The validation should fail as the entryIds are not matching. I tested this with some online validators and they all failed, but it passes using `jsonschema.validate`. Any clues? what am I missing here?

**Comment by omenlabs** [comment]
It looks like `contains` was added post `2.6.0`.

https://github.com/Julian/jsonschema/commit/497dfec2a314a7962444caabb67a0e783a510ecf#diff-66289c46b2d9052f921a55730be5c8bd

However, you can extend one of the validators in 2.6.0 with contains:

```
#!/usr/bin/env python

import jsonschema

print(jsonschema.__version__)

event = {
   "event": "entry.u",
   "timestamp": 1546467787.4796588,
   "data": {
     "orgId": 316,
     "requestId": 1128121473,
     "entryIds": [
          98, 9
     ]
   }
 }

t = {
   "properties": {
     "event": {
       "enum": [
         "un",
         "entry.u"
       ]
     },
     "data": {
       "required": ["entryIds"],
       "properties": {
         "entryIds": {
             "type": "array",
             "contains": { "enum":[ 98] }
         }
       }
     }
   },
   "required": [
     "event"
   ]
 }

# Validator for contains from v3.0.0a3
def contains(validator, contains, instance, schema):
    if not validator.is_type(instance, "array"):
        return

    if not any(validator.is_valid(element, contains) for element in instance):
        yield jsonschema.ValidationError(
            "XXX"
        )

myV = jsonschema.validators.extend(jsonschema.Draft4Validator, {u"contains": contains}, version='draft6ish')

validator = myV(t)

print("Next line should be None")
print(validator.validate(event))
print("Now we explode")
event["data"]["entryIds"] = [99]
print(validator.validate(event))
```
Output:
```
$ ./test.py 
2.6.0
Next line should be None
None
Now we explode
Traceback (most recent call last):
  File "./test.py", line 59, in <module>
    print(validator.validate(event))
  File "/home/jjh/.pyenv/py3/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: XXX

Failed validating 'contains' in schema['properties']['data']['properties']['entryIds']:
    {'contains': {'enum': [98]}, 'type': 'array'}

On instance['data']['entryIds']:
    [99]
```

**Comment by Julian** [comment]
`contains` is draft-6 only, yes (and it looks like your schema doesn't declare itself under a version, which it should with a `$schema` property).

You'd need to use one of the prereleases, or sure, extend the one you've got.

**Comment by sunshare10** [comment]
Dear Mr.fantamiracle，i'm a student of Shanghai Jiao Tong University，and i'm interested in encrypted traffic classification.recently i had read your paper:An Information-Theoretical Approach to High-Speed Flow Nature Identification.but i had some troubles in Experimental reconstruction。I would be very grateful if you can send me your code to learni.my email address is 1272763247@qq.com
