### ISSUE TITLE
get_distribution assertion when used in application packaged with pyinstaller

### ISSUE THREAD

**Issue by cc10512** [Julian/jsonschema#534]
The commit b07d0f1d893f4a21008e0c8922959ddcf0614b73 added retrieving the version using pkg_resources.get_distribution. This seems to break the initialization when the jsonschema module is included in a pyinstaller (http://www.pyinstaller.org/) generated executable. An example trace is below. Note that the same script works fine when it is not packaged with pyinstaller. Our current solution was to go back to jsonschema 2.6.0 which works in both scenarios. Please let us know if there is any hidden module that should be added to the pyinstaller setup, or any other method to register jsonschema with pkg_resources.
```
Traceback (most recent call last):
  File "build-json-logs", line 36, in <module>
  File "/tmp/pip-build-A5sYoJ/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "tools/create_json.py", line 24, in <module>
  File "/tmp/pip-build-A5sYoJ/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "jsonschema/__init__.py", line 33, in <module>
  File "pkg_resources/__init__.py", line 476, in get_distribution
  File "pkg_resources/__init__.py", line 352, in get_provider
  File "pkg_resources/__init__.py", line 895, in require
  File "pkg_resources/__init__.py", line 781, in resolve
pkg_resources.DistributionNotFound: The 'jsonschema' distribution was not found and is required by the application
```

**Comment by Julian** [comment]
Hi, sorry you're having trouble.

Please see https://github.com/Julian/jsonschema/issues/530#issuecomment-466984725.
