### ISSUE TITLE
incorrect anyOf validation error

### ISSUE THREAD

**Issue by ralphie0112358** [Julian/jsonschema#598]
This seems like a new issue in jsonschema>=3.0.

test.py
```
import jsonschema

schema = {'anyOf': [{'type': 'object'}, {'type': 'string'}]}
jsonschema.validate('hello, world', schema)
jsonschema.validate({'hello': 'world'}, schema)
jsonschema.validate(1, schema)
```

test with jsonschema==2.6.0, gives proper validation error: `1 is not valid under any of the given schemas`
```
$ rm -rf env
$ virtualenv --python=python3.7 env
Running virtualenv with interpreter /usr/bin/python3.7
Using base prefix '/usr'
/usr/lib/python3/dist-packages/virtualenv.py:1082: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /home/ubuntu/dev/jsonschema/env/bin/python3.7
Also creating executable in /home/ubuntu/dev/jsonschema/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
$ env/bin/pip install jsonschema==2.6.0
Collecting jsonschema==2.6.0
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Installing collected packages: jsonschema
Successfully installed jsonschema-2.6.0
$ env/bin/python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    jsonschema.validate(1, schema)
  File "/home/ubuntu/dev/jsonschema/env/lib/python3.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/ubuntu/dev/jsonschema/env/lib/python3.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 1 is not valid under any of the given schemas

Failed validating 'anyOf' in schema:
    {'anyOf': [{'type': 'object'}, {'type': 'string'}]}

On instance:
    1
```

test with jsonschema==3.0.2 gives wrong validation error: `1 is not of type 'object'`
```
$ rm -rf env
$ virtualenv --python=python3.7 env
Running virtualenv with interpreter /usr/bin/python3.7
Using base prefix '/usr'
/usr/lib/python3/dist-packages/virtualenv.py:1082: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /home/ubuntu/dev/jsonschema/env/bin/python3.7
Also creating executable in /home/ubuntu/dev/jsonschema/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
$ env/bin/pip install jsonschema==3.0.2
Collecting jsonschema==3.0.2
  Using cached https://files.pythonhosted.org/packages/54/48/f5f11003ceddcd4ad292d4d9b5677588e9169eef41f88e38b2888e7ec6c4/jsonschema-3.0.2-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from jsonschema==3.0.2)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting six>=1.11.0 (from jsonschema==3.0.2)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pyrsistent>=0.14.0 (from jsonschema==3.0.2)
Requirement already satisfied: setuptools in ./env/lib/python3.7/site-packages (from jsonschema==3.0.2) (41.2.0)
Installing collected packages: attrs, six, pyrsistent, jsonschema
Successfully installed attrs-19.1.0 jsonschema-3.0.2 pyrsistent-0.15.4 six-1.12.0
$ env/bin/python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    jsonschema.validate(1, schema)
  File "/home/ubuntu/dev/jsonschema/env/lib/python3.7/site-packages/jsonschema/validators.py", line 899, in validate
    raise error
jsonschema.exceptions.ValidationError: 1 is not of type 'object'

Failed validating 'type' in schema[0]:
    {'type': 'object'}

On instance:
    1
```

Thank you in advance.

**Comment by Julian** [comment]
Hi. This looks like likely a duplicate of #535. Have a look there, thanks.

**Comment by ralphie0112358** [comment]
Hi @Julian, thank you for the reply.
 
per your comment on #535:
"In 3.0 the simple validate API raises the best matched error rather than
the first encountered one. Doing so is in general easier to understand for
new users.

If you want different behavior, use a Validator instance instead."

I tried it on my test above and I get the old style error `1 is not valid under any of the given schemas`.  I don't love this but it'll have to do.   

Thank you for the library.
