### ISSUE TITLE
Json Pointer Refs fail to resolve when multiple hops are involved

### ISSUE THREAD

**Issue by FrederikP** [Julian/jsonschema#657]
Hi,
I use a third party tool, not related to this library, to bundle a multi-file schema into one file. The resulting file still contains refs pointing to other parts of the same file using json pointers. In some cases these involve multiple hops. I couldn't find anything saying that this is illegal, but this jsonschema library has an issue with that.

I came up with a really short (and thus kinda stupid) example to reproduce this:

example_deref_bug_small.json:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Example for JSON Pointer deref issue",
    "type": "object",
    "properties": {
        "ExampleProperty": {
            "type": "object",
            "properties": {
                "InnerProperty": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "InnerProperty"
            ]
        },
        "ExampleProperty2": {
            "$ref": "#/properties/ExampleProperty"
        },
        "ExampleProperty3": {
            "$ref": "#/properties/ExampleProperty2"
        }
    },
    "required": [
        "ExampleProperty",
        "ExampleProperty2",
        "ExampleProperty3"
    ]
}
```

Script to validate:
```python
import json

import jsonschema


example = {
    'ExampleProperty': {
        'InnerProperty': 'meh'
    },
    'ExampleProperty2': {
        'InnerProperty': 'meh'
    },
    'ExampleProperty3': {
        'InnerProperty': 'meh'
    }

}

with open('example_deref_bug_small.json', 'r') as schema_file:
    loaded_schema = json.load(schema_file)

jsonschema.validate(example, loaded_schema)
print('success')
```

Running the script throws this error:

```
Traceback (most recent call last):
  File "/bla/lib/python3.6/site-packages/jsonschema/validators.py", line 811, in resolve_fragment
    document = document[part]
KeyError: 'ExampleProperty1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deref_bug_script.py", line 22, in <module>
    jsonschema.validate(example, loaded_schema)
  File "/bla/lib/python3.6/site-packages/jsonschema/validators.py", line 932, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/bla/lib/python3.6/site-packages/jsonschema/exceptions.py", line 367, in best_match
    best = next(errors, None)
  File "/bla/lib/python3.6/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/bla/lib/python3.6/site-packages/jsonschema/_validators.py", line 286, in properties
    schema_path=property,
  File "/bla/lib/python3.6/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/bla/lib/python3.6/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/bla/lib/python3.6/site-packages/jsonschema/_validators.py", line 259, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/bla/lib/python3.6/site-packages/jsonschema/validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "/bla/lib/python3.6/site-packages/jsonschema/validators.py", line 781, in resolve_from_url
    return self.resolve_fragment(document, fragment)
  File "/bla/lib/python3.6/site-packages/jsonschema/validators.py", line 814, in resolve_fragment
    "Unresolvable JSON pointer: %r" % fragment
jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'properties/ExampleProperty1'
```

As soon as you change the schema, so that `ExampleProperty3` directly points to `ExampleProperty` instead of `ExampleProperty2` it works. But since the resulting schema that the third party tool creates is much more complex, in my case, I can't easily get rid of these multi-hop pointers.

Is this a bug or is following multiple pointers not allowed? Other libraries (including ones in other languages) are okay with that example schema. Example in nodejs:

```javascript
var Validator = require('jsonschema').Validator;
var v = new Validator();
example = {
    'ExampleProperty': {
        'InnerProperty': 'meh'
    },
    'ExampleProperty2': {
        'InnerProperty': 'meh'
    },
    'ExampleProperty3': {
        'InnerProperty': 'meh'
    }

}

var fs = require("fs");
var content = fs.readFileSync("example_deref_bug_small.json");
var schema = JSON.parse(content);
console.log(v.validate(example, schema));
```

**Comment by Julian** [comment]
I don't think what you're running is what you pasted.

You can see your traceback is complaining about a missing `ExampleProperty1`, but your code doesn't have such a ref, just `ExampleProperty`, and `2` and `3`.

**Comment by FrederikP** [comment]
Hey thanks for taking a look. Oh you're right I forgot to update the trace, after deciding to rename that. It shouldn't change the underlying issue though. I'll run it again and update the trace asap to make sure everything matches.

**Comment by FrederikP** [comment]
I can't reproduce it, even with my more complex example. No idea what I did there, maybe used a very old version, not sure.
I'll close this, sorry for the trouble.
