### ISSUE TITLE
600.03 is not a multiple of 0.01

### ISSUE THREAD

**Issue by ra-coder** [Julian/jsonschema#679]
```
>>> jsonschema.validate(600.03, {'$schema': 'http://json-schema.org/draft-07/schema#', 'type': 'number', 'multipleOf': 0.01})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 600.03 is not a multiple of 0.01

Failed validating 'multipleOf' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     'multipleOf': 0.01,
     'type': 'number'}

On instance:
    600.03
>>> jsonschema.__version__
'3.2.0'


```

**Comment by ra-coder** [comment]
can be fixed via 

`{ "type": "number", "multipleOfPrecision": 0.01 }`

**Comment by jsenecal** [comment]
Raising awareness here, `multipleOfPrecision` actualy **diables** validation altogether.
