### ISSUE TITLE
Running the tox –e py37-tests command on win10 keeps reporting errors

### ISSUE THREAD

**Issue by WilliamHeaven** [Julian/jsonschema#699]
## The test steps are as follows：
* pip install tox
* pip install tox-venv
* tox –e py37-tests 
## Environmental information is as follows：
![image](https://user-images.githubusercontent.com/28834227/85937654-3c591680-b938-11ea-98bc-c8bccbebc474.png)
## Report an error：
[error.log](https://github.com/Julian/jsonschema/files/4841667/error.log)
```
Wheel checks failed                                         W-__main__
Checks failed
ERROR: InvocationError for command 'D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-build\Scripts\python' -m pep517.check 'D:\OpenSourc
e\Project\python_workspace\jsonschema-master' (exited with code 1)
py37-tests installed: attrs==19.3.0,Automat==20.2.0,constantly==15.1.0,hyperlink==19.0.0,idna==2.9,incremental==17.5.0,PyHamcrest==2.0.2,six==1.15.0,Twist
ed==20.3.0,zope.interface==5.1.0
py37-tests run-test-pre: PYTHONHASHSEED='822'
py37-tests run-test: commands[0] | 'D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-tests\Scripts\python' -m pip install 'D:\OpenSource
\Project\python_workspace\jsonschema-master[format]'
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing d:\opensource\project\python_workspace\jsonschema-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-tests\Scripts\python.exe' 'D:\OpenSource\Project\python_workspace\jsonsche
ma-master\.tox\py37-tests\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\jwx592110\AppData\Local\Temp\tmpnj3j
3uzm'
       cwd: C:\Users\jwx592110\AppData\Local\Temp\pip-req-build-z1mo9k8s
  Complete output (35 lines):
  Traceback (most recent call last):
    File "D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-tests\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <mod
ule>
      main()
    File "D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-tests\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main

      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-tests\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_r
equires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools\build_meta.py", line 147, in get_requires_for_
build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools\build_meta.py", line 127, in _get_build_requir
es
      self.run_setup()
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 1, in <module>
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools\__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "d:\software\installpath\python37_64\lib\distutils\core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools\dist.py", line 426, in __init__
      k: v for k, v in attrs.items()
    File "d:\software\installpath\python37_64\lib\distutils\dist.py", line 292, in __init__
      self.finalize_options()
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools\dist.py", line 717, in finalize_options
      ep(self)
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools_scm\integration.py", line 48, in infer_version

      dist.metadata.version = _get_version(config)
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 148, in _get_version
      parsed_version = _do_parse(config)
    File "C:\Users\jwx592110\AppData\Local\Temp\pip-build-env-lqvi7o6a\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 118, in _do_parse
      "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
  LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\jwx592110\\AppData\\Local\\Temp\\pip-req-build-z1mo9k8s'.
  
  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout with
out the .git folder) don't contain the necessary metadata and will not work.
  
  For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-tests\Scripts\python.exe' 'D:\OpenSourc
e\Project\python_workspace\jsonschema-master\.tox\py37-tests\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\j
wx592110\AppData\Local\Temp\tmpnj3j3uzm' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
ERROR: InvocationError for command 'D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-tests\Scripts\python' -m pip install 'D:\OpenSource
\Project\python_workspace\jsonschema-master[format]' (exited with code 1)
py37-tests_nongpl create: D:\OpenSource\Project\python_workspace\jsonschema-master\.tox\py37-tests_nongpl
py37-tests_nongpl installdeps: -rD:\OpenSource\Project\python_workspace\jsonschema-master/test-requirements.txt, twisted
ERROR: got KeyboardInterrupt signal
```

**Comment by Julian** [comment]
Hey. Are you in fact running from a tarball as the error says?

I don't really have access to Windows personally. But Windows is supported for end-users (and passes in CI running that tox command).

**Comment by WilliamHeaven** [comment]
I ran from the compressed package, and now I change the way, it's ok, thank you very much!

**Comment by WilliamHeaven** [comment]
The contents of the zip package and the git cloned package are the same. Why is there a difference in running the test?

**Comment by Julian** [comment]
They aren't the same, one isn't a git repo :) which is required for version info. Only running the tests on a full checkout or on an installed package are the two supported development modes.
