### ISSUE TITLE
Error importing jsonschema in Python 2.7

### ISSUE THREAD

**Issue by norseman99** [Julian/jsonschema#763]
From what I was able to understand jsonschema 3.2.0 is using a lib called pyrsistent that uses Python 3 synthax, which makes jsonschema not able to work in python 2.7.

```
Traceback (most recent call last):
  File "schema_validator.py", line 3, in <module>
    import jsonschema
  File "/.../Python/2.7/lib/python/site-packages/jsonschema/__init__.py", line 21, in <module>
    from jsonschema._types import TypeChecker
  File "/.../Python/2.7/lib/python/site-packages/jsonschema/_types.py", line 3, in <module>
    from pyrsistent import pmap
  File "/.../Python/2.7/lib/python/site-packages/pyrsistent/__init__.py", line 3, in <module>
    from pyrsistent._pmap import pmap, m, PMap
  File "/.../Python/2.7/lib/python/site-packages/pyrsistent/_pmap.py", line 98
    ) from e
```

**Comment by norseman99** [comment]
As an additional information, downgrading pyrsistent from 0.17.2 to 0.16.0 resolves the issue.

**Comment by Julian** [comment]
Hi there -- this almost always means you installed `jsonschema` with an old version of pip (like 2 year plus old) -- `pyrsistent` declares that 0.17.x doesn't support Py2, but if you have too old a pip, it won't know how to respect that setting.
