### ISSUE TITLE
Failed to validate valid object with "properties" property

### ISSUE THREAD

**Issue by avida** [Julian/jsonschema#829]
This code:
```python
from jsonschema import validate

schema = {
  "type": "object",
  "properties": {"someId": {"type": "number"},
                "status": {"type": "string"},
                "properties": {"type": "string"}},
  "required": ["someId", "status"]
 }

obj = {
 "someId": 0,
 "status": "one",
 "properties": "ss"
}

validate(schema, obj)
```
python version 3.8
jsonschema version 3.2.0
**Expected result:**
    No exception since object is valid
**Actual resu**lt: 
Validation exception
```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    validate(schema, obj)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/jsonschema/validators.py", line 930, in validate
    cls.check_schema(schema)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/jsonschema/validators.py", line 294, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: 'ss' is not of type 'object'

Failed validating 'type' in metaschema['properties']['properties']:
    {'additionalProperties': {'$ref': '#'}, 'default': {}, 'type': 'object'}

On schema['properties']:
    'ss'

```

**Comment by avida** [comment]
Look like validate function misuse, this works fine:
```python
validate(schema=schema, instance=obj)
```
