### ISSUE TITLE
RecursionError when validating schema with anyOf and no recursion

### ISSUE THREAD

**Issue by Zeckie** [Julian/jsonschema#847]
A python project i'm working on recently started failing with a RecursionError. We are using jsonschema to validate quite a complex yaml file, but i've been able to cut that down to few lines.

Issue occured when using jsonschema==4.0.1 on Python 3.9.6, but did not occur with jsonschema==3.2.0

```python
from jsonschema.validators import validate
validate(
    instance={"foo": "bar"},
    schema={
        "$schema": "https://json-schema.org/draft/2019-09/schema",
        "anyOf": [{"type": "object"}],
    },
)
```
Gives:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\...\Python\Python39\lib\site-packages\jsonschema\validators.py", line 963, in validate
    cls.check_schema(schema)
  File "C:\...\Python\Python39\lib\site-packages\jsonschema\validators.py", line 182, in check_schema
    for error in cls(cls.META_SCHEMA).iter_errors(schema):
  File "C:\...\Python\Python39\lib\site-packages\jsonschema\validators.py", line 224, in iter_errors
    for error in errors:
  File "C:\...\Python\Python39\lib\site-packages\jsonschema\_validators.py", line 359, in allOf
    yield from validator.descend(instance, subschema, schema_path=index)
  File "C:\...\Python\Python39\lib\site-packages\jsonschema\validators.py", line 240, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "C:\...\Python\Python39\lib\site-packages\jsonschema\validators.py", line 224, in iter_errors
... 
  File "C:\...\Python\Python39\lib\site-packages\jsonschema\_legacy_validators.py", line 216, in recursiveRef
    lookup_url, next_target = validator.resolver.resolve(each)
  File "C:\...\Python\Python39\lib\site-packages\jsonschema\validators.py", line 775, in resolve
    uri, fragment = urldefrag(url)
  File "C:\...\Python\Python39\lib\urllib\parse.py", line 602, in urldefrag
    s, n, p, a, q, frag = urlparse(url)
  File "C:\...\Python\Python39\lib\urllib\parse.py", line 393, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "C:\...\Python\Python39\lib\urllib\parse.py", line 458, in urlsplit
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "C:\...\Python\Python39\lib\urllib\parse.py", line 120, in _coerce_args
    str_input = isinstance(args[0], str)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by Julian** [comment]
Hi there. This probably indeed is a bug, but just to clarify, you mean you created a new example different than the one you had previously been using correct?

jsonschema 3.2.0 didn't support draft2019-09, so the schema you have here wouldn't have done anything on that version.

**Comment by Zeckie** [comment]
I didn't realize that draft 2019-09 was not supported on 3.2.0. We have been using that combination for a while, and presumably the metaschema was being ignored. The `instance` was still being validated against the `schema`.

Our actual project contains a lot more in the instance and schema, and gets the data for both from yaml files. When posting this issue, I cut out everything that what was not required to reproduce the error.

I have tried a few different versions (with both the cut down code posted here, and our full project), and looks like this issue only occurs with `https://json-schema.org/draft/2019-09/schema`.

**Comment by robherring** [comment]
FWIW, I'm seeing what appears to be the same problem if using draft 2019-09 meta-schema.

**Comment by Zeckie** [comment]
@robherring does your schema use "anyOf"?

**Comment by robherring** [comment]
@Zeckie Yes, it does. I would think the problem exists for other cases as well. 'allOf' has the same meta-schema for example.

**Comment by olegshtch** [comment]
I suppose https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#appendix-C tree example couldn't be validated with the same error?

**Comment by andylamp** [comment]
Just to chip in on this - does the issue occur with the Draft `2020-12` or just the "old" `2019-09`?

Using the latest version of the package, namely  v4.4.0 seems to... work without crashing...?

```python
from jsonschema.validators import validate

# this is OK...?
validate(
	instance={"foo": "bar"},
	schema={
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"anyOf": [{"type": "object"}],
	},
)

# this exhibits the error described in the thread.
validate(
	instance={"foo": "bar"},
	schema={
		"$schema": "https://json-schema.org/draft/2019-09/schema",
		"anyOf": [{"type": "object"}],
	},
)
```

Can anyone confirm this behavior?

**Comment by mg-christian-axelsson** [comment]
> Can anyone confirm this behavior?

Yes. I was hit by this last week and just found out about this issue.

**Comment by jrodriguezs92** [comment]
Facing the same issue in version 4.3.1 and 4.5.1, using `"$schema": "https://json-schema.org/draft/2019-09/schema"` and with schema containing `allOf` and `minContains`
Does this have any solution yet?

**Comment by Julian** [comment]
As I mentioned:

https://github.com/python-jsonschema/jsonschema/issues/847#issuecomment-937941431
