### ISSUE TITLE
ModuleNotFoundError: No module named 'jsonschema.compat'

### ISSUE THREAD

**Issue by MasterGeorges67** [Julian/jsonschema#851]
I using the pybit project, which is using also the jsonschema.
Since updating to version 4.0.1 I get the following error:
========
Traceback (most recent call last):
  File "E:\programming\Project\TradeBot\TradingBot.py", line 12, in <module>
    from bybit import HTTP
  File "E:\programming\Project\TradeBot\env\lib\site-packages\bybit\__init__.py", line 3, in <module> 
    from bravado.client import SwaggerClient
  File "E:\programming\Project\TradeBot\env\lib\site-packages\bravado\client.py", line 51, in <module>
    from bravado_core.param import marshal_param
  File "E:\programming\Project\TradeBot\env\lib\site-packages\bravado_core\param.py", line 13, in <module>
    from bravado_core.marshal import marshal_schema_object
    from bravado_core.model import Model
  File "E:\programming\Project\TradeBot\env\lib\site-packages\bravado_core\model.py", line 13, in <module>
    from swagger_spec_validator.ref_validators import attach_scope
  File "E:\programming\Project\TradeBot\env\lib\site-packages\swagger_spec_validator\__init__.py", line 8, in <module>
    from swagger_spec_validator.util import validate_spec_url
  File "E:\programming\Project\TradeBot\env\lib\site-packages\swagger_spec_validator\util.py", line 9, in <module>
    from swagger_spec_validator import validator12
  File "E:\programming\Project\TradeBot\env\lib\site-packages\swagger_spec_validator\validator12.py", line 29, in <module>
    from swagger_spec_validator.ref_validators import default_handlers
  File "E:\programming\Project\TradeBot\env\lib\site-packages\swagger_spec_validator\ref_validators.py", line 14, in <module>
    from jsonschema.compat import iteritems
ModuleNotFoundError: No module named 'jsonschema.compat'
========
Any help or ideas?
Regards,

**Comment by Julian** [comment]
Hi there. This is a downstream bug you should file on swagger-spec-validator, unless you see it filed already.

More context in #843.

**Comment by MasterGeorges67** [comment]
Thanks for the reply, but I using bybit and if I go back to the version 3.1.1 of jsonschema, all is running correct.
I give back your replay to the bybit developer.
Regards,
