### ISSUE TITLE
AttributeError: module 'importlib_resources' has no attribute 'files'

### ISSUE THREAD

**Issue by moorepants** [Julian/jsonschema#921]
`conda env` commands are failing with:

```
$ conda env list
Traceback (most recent call last):
  File "/home/moorepants/miniconda/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/conda_env/cli/main.py", line 44, in <module>
    from . import main_create
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 19, in <module>
    from .. import exceptions, specs
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 9, in <module>
    from .notebook import NotebookSpec
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/conda_env/specs/notebook.py", line 5, in <module>
    import nbformat
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/nbformat/__init__.py", line 32, in <module>
    from .validator import validate, ValidationError
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/nbformat/validator.py", line 12, in <module>
    from .json_compat import get_current_validator, ValidationError
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/nbformat/json_compat.py", line 10, in <module>
    import jsonschema
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jsonschema/__init__.py", line 29, in <module>
    from jsonschema.protocols import Validator
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jsonschema/protocols.py", line 33, in <module>
    from jsonschema.validators import RefResolver
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jsonschema/validators.py", line 356, in <module>
    meta_schema=_utils.load_schema("draft3"),
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jsonschema/_utils.py", line 60, in load_schema
    path = resources.files(__package__).joinpath(f"schemas/{name}.json")

```
See: https://github.com/conda/conda/issues/11270

I have jsonschema 4.4.0 installed from conda-forge.

**Comment by moorepants** [comment]
I downgraded to jsonschema 3.2.0 and `conda env` command work.

**Comment by Julian** [comment]
Hi -- can you provide a full reproducer, this should work fine, e.g. indeed `importlib_resources.files` exists:

```
⊙  python3 -m venv venv; venv/bin/python -m pip install importlib_resources; venv/bin/python -c 'import importlib_resources; print(importlib_resources.files)'                      julian@Airm
Collecting importlib_resources
  Using cached importlib_resources-5.4.0-py3-none-any.whl (28 kB)
Installing collected packages: importlib_resources
Successfully installed importlib_resources-5.4.0
<function files at 0x10282b010>
```

but hard to know what has gone wrong in your case.

**Comment by moorepants** [comment]
The reproducer is just "conda env list" with conda 4.11.0 and jsonschema 4.4.0.

**Comment by Julian** [comment]
Thanks, but as I say, it'd be helpful if you provide a reproducer command which demonstrates the issue. I don't use `conda`, and as I've demonstrated, things work here (both in CI, and just directly installing the library you're referencing).

**Comment by moorepants** [comment]
I'm not familiar with conda's source code, so that's the best I can do without digging deep through that stacktrace. I'm guessing the issue must be higher up the dependency stack. Maybe nbformat is using API that changed in jsonschema from 3.2 to 4.4.

**Comment by Julian** [comment]
My guess without any info would actually be more like that conda is installing or depending on a very old version of `importlib_resources`, but it's a bit impossible to guess. What I am asking is to provide me some way of getting the same environment that you have without assuming I know how to do so :)

I would be quite surprised if this was an issue with jsonschema, but anything's possible, which is why the above would be helpful.

**Comment by moorepants** [comment]
This is what is installed for importlib:
```
importlib-metadata        4.11.1           py37h89c1867_0    conda-forge
importlib_metadata        4.11.1               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
```

**Comment by moorepants** [comment]
You can see all the packages installed here: https://github.com/conda/conda/issues/11270 under `conda list`.

Reproducing the environment is a bit tricky because it has so many packages. I'll have to export a conda environment file, but I'll have to do that later, as I'm about to go to sleep.

**Comment by moorepants** [comment]
A conda dev stated that jsonschema >= 4 breaks conda and that I have to downgrade. I've opened a fix here https://github.com/conda-forge/conda-feedstock/pull/160, so I'll close this as it isn't a bug with this package. Sorry for the noise.
