### ISSUE TITLE
validating an invalid json based on schema AllOf

### ISSUE THREAD

**Issue by hybrid461** [Julian/jsonschema#922]
I've run into what I assume must be a bug as I can get the data to be invalid on jsonschemalint.com. Using version 4.4.0 from pypi.

Data sample:
```
{
    "bbb":
    {
        "information":
        {
            "Name-Real": "bbb bbb",
            "Name-Email": "bbb@mail.com",
            "Passphrase": "abc123"
        },
        "keys": {
            "private_key": "file1",
            "public_key": "file2",
            "recipient_key": "file3"
        }
    }
}
```

Schema:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Keypair configuration schema",
    "description": "Used to validate each keypair entry in the config",
    "type": "object",
    "patternProperties": {
        "^[\\w,-]+$": {
            "description": "name of the keypair, must match a folder name",
            "type": "object",
            "properties": {
                "information": {
                    "description": "identifiers and passphrase for the keypair",
                    "type": "object",
                    "properties": {
                        "Name-Real": {
                            "type": "string"
                        },
                        "Name-Email": {
                            "type": "string"
                        },
                        "Passphrase": {
                            "type": "string"
                        },
                        "Recipient": {
                            "type": "string"
                        }
                    },
                    "required": ["Name-Real", "Passphrase"]
                },
                "keys":{
                    "description": "filenames of keys to be found on disk",
                    "type": "object",
                    "properties":{
                        "private_key": {
                            "type": "string"
                        },
                        "public_key": {
                            "type": "string"
                        },
                        "recipient_key": {
                            "type": "string"
                        }
                    },
                    "required": ["private_key", "public_key"]
                }
            },
            "allOf": [
                {
                    "if": {
                        "properties": {
                            "information": {
                                "type": "object",
                                "properties": {
                                    "Recipient": {
                                        "type": "string"}
                                },
                                "required": ["Recipient"]
                            }
                        }
                    },
                    "then": {
                        "properties": {
                            "keys": {
                                "type": "object",
                                "properties": {
                                    "recipient_key": {
                                        "type": "string"}
                                },
                                "required": ["recipient_key"]
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "keys": {
                                "type": "object",
                                "properties": {
                                    "recipient_key": {
                                        "type": "string"}
                                },
                                "required": ["recipient_key"]
                            }
                        }
                    },
                    "then": {
                        "properties": {
                            "information": {
                                "type": "object",
                                "properties": {
                                    "Recipient": {
                                        "type": "string"
                                    }
                                },
                                "required": ["Recipient"]
                            }
                        }
                    }
                }
            ]
        }
    }
}
```

Code:
```
import json
from jsonschema import validate, ValidationError

schema_file = 'schema.json'
test_file = 'fail1.json'

def json_validate(json_obj, schema):
    try:
        validate(instance=json_obj, schema=schema)
        return True, None
    except ValidationError as e:
        return False, e


def main():
    print(f"opening {schema_file}")
    with open(schema_file) as sfd:
        schema = json.load(sfd)
    with open(test_file) as tfd:
        content = json.load(tfd)
    print(content)
    result, err = json_validate(content, schema)
    print(f"File:{test_file}. validated:{result}. Error:{err}")

if __name__ == '__main__':
    main()
```

The result returns True with no error

**Comment by Julian** [comment]
Hi. Can you minimize your example so it contains the least sized instance and schema that exhibits the behavior that surprises you?

**Comment by hybrid461** [comment]
Sure thing.

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Keypair configuration schema",
    "description": "Used to validate each keypair entry in the config",
    "type": "object",
    "patternProperties": {
        "^[\\w,-]+$": {
            "allOf": [
                {
                    "if": {
                        "properties": {
                            "keys": {
                                "type": "object",
                                "properties": {
                                    "recipient_key": {
                                        "type": "string"}
                                },
                                "required": ["recipient_key"]
                            }
                        }
                    },
                    "then": {
                        "properties": {
                            "information": {
                                "type": "object",
                                "properties": {
                                    "Recipient": {
                                        "type": "string"
                                    }
                                },
                                "required": ["Recipient"]
                            }
                        }
                    }
                }
            ]
        }
    }
}
```

So what this should do is check if the property recipient_key exists within the keys object, and is a string, then the Recipient property which is stored within the information object should also exist.

As per my sample data above, this is not the case.

**Comment by Julian** [comment]
For me that produces:

```python
import jsonschema
instance = {
    "bbb": {
        "information":
        {
            "Name-Real": "bbb bbb",
            "Name-Email": "bbb@mail.com",
            "Passphrase": "abc123"
        },
        "keys": {
            "private_key": "file1",
            "public_key": "file2",
            "recipient_key": "file3"
        }
    }
}

schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Keypair configuration schema",
    "description": "Used to validate each keypair entry in the config",
    "type": "object",
    "patternProperties": {
        "^[\\w,-]+$": {
            "allOf": [
                {
                    "if": {
                        "properties": {
                            "keys": {
                                "type": "object",
                                "properties": {
                                    "recipient_key": {
                                        "type": "string"}
                                },
                                "required": ["recipient_key"]
                            }
                        }
                    },
                    "then": {
                        "properties": {
                            "information": {
                                "type": "object",
                                "properties": {
                                    "Recipient": {
                                        "type": "string"
                                    }
                                },
                                "required": ["Recipient"]
                            }
                        }
                    }
                }
            ]
        }
    }
}
jsonschema.validate(instance, schema)
```

```
Traceback (most recent call last):
  File "/Users/julian/Desktop/foo.py", line 57, in <module>
    jsonschema.validate(instance, schema)
  File "/Users/julian/.dotfiles/.local/share/virtualenvs/jsonschema/lib/python3.10/site-packages/jsonschema/validators.py", line 967, in validate
    raise error
jsonschema.exceptions.ValidationError: 'Recipient' is a required property

Failed validating 'required' in schema['patternProperties']['^[\\w,-]+$']['allOf'][0]['then']['properties']['information']:
    {'properties': {'Recipient': {'type': 'string'}},
     'required': ['Recipient'],
     'type': 'object'}

On instance['bbb']['information']:
    {'Name-Email': 'bbb@mail.com',
     'Name-Real': 'bbb bbb',
     'Passphrase': 'abc123'}
```

what result are you expecting? Also again it'd be helpful to minimize what you have there further. E.g. remove unneeded properties both from your schema and instance.

**Comment by hybrid461** [comment]
Thanks Julian, that sample you posted does work for me too. It must have something to do with loading the data. Thanks for your time.
